[package]
name = "diswall"
version = "0.5.2"
edition = "2021"
homepage = "https://diswall.stream"
repository = "https://github.com/dis-works/diswall-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
log = "0.4.21"
simplelog = "0.12.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
rmp-serde = "1.1.2"
toml = "0.8.11"
json = "0.12.4"
byteorder = "1.5.0"
hostname = "^0.3"
nats = "0.24.1"
sqlite = "0.34.0"
time = { version = "0.3.34", features = ["formatting"] }
rand = "0.8.5"
ureq = "^2.9"
lru = "0.12.0"
nix = { version = "0.28.0", features = ["fs"] }
ratatui = "0.26.1"
crossterm = "0.27.0"

[target.'cfg(target_os = "linux")'.dependencies]
netstat2 = "0.9.1"

[profile.release]
opt-level = 3
lto = true
strip = true  # Automatically strip symbols from the binary.
